# DATABASE - STAGING / NEON
spring.datasource.url=${NEON_DATABASE_URL}
spring.datasource.username=${NEON_DATABASE_USER}
spring.datasource.password=${NEON_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.expiration-ms=7200000

# FRONTEND / CORS
app.frontend.base-url=${FRONTEND_BASE_URL}
app.cors.allowed-origins=${FRONTEND_BASE_URL}

# SWAGGER
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true